<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Anderson dos Santos Silva">
<meta name="author" content="José Alves de Figueiredo Neto">

<title>Análise de Correlação e Regressão Linear Simples</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="relatorio_files/libs/clipboard/clipboard.min.js"></script>
<script src="relatorio_files/libs/quarto-html/quarto.js"></script>
<script src="relatorio_files/libs/quarto-html/popper.min.js"></script>
<script src="relatorio_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="relatorio_files/libs/quarto-html/anchor.min.js"></script>
<link href="relatorio_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="relatorio_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="relatorio_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="relatorio_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="relatorio_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Sumário</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução"><span class="toc-section-number">1</span>  Introdução</a>
  <ul class="collapse">
  <li><a href="#carregando-pacotes" id="toc-carregando-pacotes" class="nav-link" data-scroll-target="#carregando-pacotes"><span class="toc-section-number">1.1</span>  Carregando pacotes</a></li>
  <li><a href="#leitura-dos-dados" id="toc-leitura-dos-dados" class="nav-link" data-scroll-target="#leitura-dos-dados"><span class="toc-section-number">1.2</span>  Leitura dos Dados</a>
  <ul class="collapse">
  <li><a href="#carregando-os-dados" id="toc-carregando-os-dados" class="nav-link" data-scroll-target="#carregando-os-dados"><span class="toc-section-number">1.2.1</span>  Carregando os Dados</a></li>
  <li><a href="#variáveis-de-interesse" id="toc-variáveis-de-interesse" class="nav-link" data-scroll-target="#variáveis-de-interesse"><span class="toc-section-number">1.2.2</span>  Variáveis de Interesse</a></li>
  <li><a href="#visualizando-os-dados" id="toc-visualizando-os-dados" class="nav-link" data-scroll-target="#visualizando-os-dados"><span class="toc-section-number">1.2.3</span>  Visualizando os Dados</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#análise-exploratória-dos-dados" id="toc-análise-exploratória-dos-dados" class="nav-link" data-scroll-target="#análise-exploratória-dos-dados"><span class="toc-section-number">2</span>  Análise Exploratória dos Dados</a>
  <ul class="collapse">
  <li><a href="#resumo-dos-dados" id="toc-resumo-dos-dados" class="nav-link" data-scroll-target="#resumo-dos-dados"><span class="toc-section-number">2.1</span>  Resumo dos Dados</a></li>
  <li><a href="#análise-descritiva-das-variáveis" id="toc-análise-descritiva-das-variáveis" class="nav-link" data-scroll-target="#análise-descritiva-das-variáveis"><span class="toc-section-number">2.2</span>  Análise Descritiva das Variáveis</a>
  <ul class="collapse">
  <li><a href="#idade-gestacional-gestwks" id="toc-idade-gestacional-gestwks" class="nav-link" data-scroll-target="#idade-gestacional-gestwks"><span class="toc-section-number">2.2.1</span>  Idade Gestacional (gestwks)</a></li>
  <li><a href="#altura-da-mãe-mheightcm" id="toc-altura-da-mãe-mheightcm" class="nav-link" data-scroll-target="#altura-da-mãe-mheightcm"><span class="toc-section-number">2.2.2</span>  Altura da Mãe (mheightcm)</a></li>
  <li><a href="#idade-da-mãe-mageyrs" id="toc-idade-da-mãe-mageyrs" class="nav-link" data-scroll-target="#idade-da-mãe-mageyrs"><span class="toc-section-number">2.2.3</span>  Idade da Mãe (mageyrs)</a></li>
  <li><a href="#peso-ao-nascer-bwtkg" id="toc-peso-ao-nascer-bwtkg" class="nav-link" data-scroll-target="#peso-ao-nascer-bwtkg"><span class="toc-section-number">2.2.4</span>  Peso ao Nascer (bwtkg)</a></li>
  <li><a href="#observações-importantes" id="toc-observações-importantes" class="nav-link" data-scroll-target="#observações-importantes"><span class="toc-section-number">2.2.5</span>  Observações Importantes</a></li>
  </ul></li>
  <li><a href="#analisando-correlações-entre-variáveis" id="toc-analisando-correlações-entre-variáveis" class="nav-link" data-scroll-target="#analisando-correlações-entre-variáveis"><span class="toc-section-number">2.3</span>  Analisando Correlações entre Variáveis</a>
  <ul class="collapse">
  <li><a href="#idade-gestacional-e-peso-ao-nascer" id="toc-idade-gestacional-e-peso-ao-nascer" class="nav-link" data-scroll-target="#idade-gestacional-e-peso-ao-nascer"><span class="toc-section-number">2.3.1</span>  Idade Gestacional e Peso ao Nascer</a></li>
  <li><a href="#altura-da-mãe-e-peso-ao-nascer" id="toc-altura-da-mãe-e-peso-ao-nascer" class="nav-link" data-scroll-target="#altura-da-mãe-e-peso-ao-nascer"><span class="toc-section-number">2.3.2</span>  Altura da Mãe e Peso ao Nascer</a></li>
  <li><a href="#idade-da-mãe-e-peso-ao-nascer" id="toc-idade-da-mãe-e-peso-ao-nascer" class="nav-link" data-scroll-target="#idade-da-mãe-e-peso-ao-nascer"><span class="toc-section-number">2.3.3</span>  Idade da Mãe e Peso ao Nascer</a></li>
  </ul></li>
  <li><a href="#visualizando-a-correlação-das-4-variáveis" id="toc-visualizando-a-correlação-das-4-variáveis" class="nav-link" data-scroll-target="#visualizando-a-correlação-das-4-variáveis"><span class="toc-section-number">2.4</span>  Visualizando a Correlação das 4 Variáveis</a></li>
  </ul></li>
  <li><a href="#análise-indutiva" id="toc-análise-indutiva" class="nav-link" data-scroll-target="#análise-indutiva"><span class="toc-section-number">3</span>  Análise Indutiva</a>
  <ul class="collapse">
  <li><a href="#peso-ao-nascer-e-idade-gestacional" id="toc-peso-ao-nascer-e-idade-gestacional" class="nav-link" data-scroll-target="#peso-ao-nascer-e-idade-gestacional"><span class="toc-section-number">3.1</span>  Peso Ao Nascer e Idade Gestacional</a></li>
  <li><a href="#peso-ao-nascer-e-altura-da-mãe" id="toc-peso-ao-nascer-e-altura-da-mãe" class="nav-link" data-scroll-target="#peso-ao-nascer-e-altura-da-mãe"><span class="toc-section-number">3.2</span>  Peso ao Nascer e Altura da Mãe</a></li>
  <li><a href="#peso-ao-nascer-e-idade-da-mãe" id="toc-peso-ao-nascer-e-idade-da-mãe" class="nav-link" data-scroll-target="#peso-ao-nascer-e-idade-da-mãe"><span class="toc-section-number">3.3</span>  Peso ao Nascer e Idade da Mãe</a></li>
  </ul></li>
  <li><a href="#análise-de-regressão-linear" id="toc-análise-de-regressão-linear" class="nav-link" data-scroll-target="#análise-de-regressão-linear"><span class="toc-section-number">4</span>  Análise de Regressão Linear</a>
  <ul class="collapse">
  <li><a href="#idade-gestacional-e-peso-ao-nascer-1" id="toc-idade-gestacional-e-peso-ao-nascer-1" class="nav-link" data-scroll-target="#idade-gestacional-e-peso-ao-nascer-1"><span class="toc-section-number">4.1</span>  Idade Gestacional e Peso Ao Nascer</a>
  <ul class="collapse">
  <li><a href="#análise-do-modelo" id="toc-análise-do-modelo" class="nav-link" data-scroll-target="#análise-do-modelo"><span class="toc-section-number">4.1.1</span>  Análise do Modelo</a></li>
  <li><a href="#verificação-dos-pressupostos-da-regressão-linear" id="toc-verificação-dos-pressupostos-da-regressão-linear" class="nav-link" data-scroll-target="#verificação-dos-pressupostos-da-regressão-linear"><span class="toc-section-number">4.1.2</span>  Verificação dos Pressupostos da Regressão Linear</a></li>
  <li><a href="#visualização-gráfica" id="toc-visualização-gráfica" class="nav-link" data-scroll-target="#visualização-gráfica"><span class="toc-section-number">4.1.3</span>  Visualização Gráfica</a></li>
  </ul></li>
  <li><a href="#altura-da-mãe-e-peso-ao-nascer-1" id="toc-altura-da-mãe-e-peso-ao-nascer-1" class="nav-link" data-scroll-target="#altura-da-mãe-e-peso-ao-nascer-1"><span class="toc-section-number">4.2</span>  Altura da Mãe e Peso ao Nascer</a>
  <ul class="collapse">
  <li><a href="#análise-do-modelo-1" id="toc-análise-do-modelo-1" class="nav-link" data-scroll-target="#análise-do-modelo-1"><span class="toc-section-number">4.2.1</span>  Análise do Modelo</a></li>
  <li><a href="#verificação-dos-pressupostos-da-regressão-linear-1" id="toc-verificação-dos-pressupostos-da-regressão-linear-1" class="nav-link" data-scroll-target="#verificação-dos-pressupostos-da-regressão-linear-1"><span class="toc-section-number">4.2.2</span>  Verificação dos Pressupostos da Regressão Linear</a></li>
  <li><a href="#visualização-gráfica-1" id="toc-visualização-gráfica-1" class="nav-link" data-scroll-target="#visualização-gráfica-1"><span class="toc-section-number">4.2.3</span>  Visualização Gráfica</a></li>
  </ul></li>
  <li><a href="#idade-da-mãe-e-peso-ao-nascer-1" id="toc-idade-da-mãe-e-peso-ao-nascer-1" class="nav-link" data-scroll-target="#idade-da-mãe-e-peso-ao-nascer-1"><span class="toc-section-number">4.3</span>  Idade da Mãe e Peso ao Nascer</a>
  <ul class="collapse">
  <li><a href="#análise-do-modelo-2" id="toc-análise-do-modelo-2" class="nav-link" data-scroll-target="#análise-do-modelo-2"><span class="toc-section-number">4.3.1</span>  Análise do Modelo</a></li>
  <li><a href="#verificação-dos-pressupostos-da-regressão-linear-2" id="toc-verificação-dos-pressupostos-da-regressão-linear-2" class="nav-link" data-scroll-target="#verificação-dos-pressupostos-da-regressão-linear-2"><span class="toc-section-number">4.3.2</span>  Verificação dos Pressupostos da Regressão Linear</a></li>
  <li><a href="#visualização-gráfica-2" id="toc-visualização-gráfica-2" class="nav-link" data-scroll-target="#visualização-gráfica-2"><span class="toc-section-number">4.3.3</span>  Visualização Gráfica</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conclusão" id="toc-conclusão" class="nav-link" data-scroll-target="#conclusão"><span class="toc-section-number">5</span>  Conclusão</a>
  <ul class="collapse">
  <li><a href="#realizando-previsões-de-peso-ao-nascer" id="toc-realizando-previsões-de-peso-ao-nascer" class="nav-link" data-scroll-target="#realizando-previsões-de-peso-ao-nascer"><span class="toc-section-number">5.1</span>  Realizando Previsões De Peso ao Nascer</a>
  <ul class="collapse">
  <li><a href="#a-partir-na-idade-gestacional" id="toc-a-partir-na-idade-gestacional" class="nav-link" data-scroll-target="#a-partir-na-idade-gestacional"><span class="toc-section-number">5.1.1</span>  A partir na Idade Gestacional</a></li>
  <li><a href="#a-partir-da-altura-da-mãe" id="toc-a-partir-da-altura-da-mãe" class="nav-link" data-scroll-target="#a-partir-da-altura-da-mãe"><span class="toc-section-number">5.1.2</span>  A partir da Altura da Mãe</a></li>
  <li><a href="#a-partir-da-idade-da-mãe" id="toc-a-partir-da-idade-da-mãe" class="nav-link" data-scroll-target="#a-partir-da-idade-da-mãe"><span class="toc-section-number">5.1.3</span>  A partir da Idade da Mãe</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Análise de Correlação e Regressão Linear Simples</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Anderson dos Santos Silva </p>
             <p>José Alves de Figueiredo Neto </p>
          </div>
  </div>
    
    
  </div>
  

</header>

<section id="introdução" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introdução</h1>
<p>O Conjunto de Dados de Saude e Desenvolvimento da Criança foi projetado para avaliar fatores relacionados ao baixo peso ao nascer em crianças. O conjunto de dados do software Stata chdsmetric.dta contém as seguintes variáveis:</p>
<ol type="1">
<li>bwtkg (birth weight, in kg) / (peso ao nascer, em kg)</li>
<li>blengthcm (birth length, in cm) / (comprimento ao nascer, em cm)</li>
<li>bheadcircm (birth head circumference, in cm) / (perímetro cefálico de nascimento, em cm)</li>
<li>gestwks (gestational age, in weeks) / (idade gestacional, em semanas)</li>
<li>mageyrs (mother’s age, in years) / (idade da mãe , em anos)</li>
<li>mheightcm (mother’s height, in cm) / (altura da mãe, em cm)</li>
<li>mweightkg (mother’s prepregnancy weight, in kg) / (peso pré-gestacional da mãe, em kg)</li>
<li>mcig (mother’s number of cigarettes smoked per day) (número de cigarros fumados pela mãe por dia)</li>
<li>fageyrs (father’s age, in years) / (idade do pai, em anos )</li>
<li>fheightcm (father’s height, in cm) / (altura do pai, em cm)</li>
<li>fedyrs (father’s education, in years) / (educação do pai, em anos)</li>
<li>fcig (father’s number of cigarettes smoked per day) / (número de cigarros fumados por dia do pai)</li>
<li>lowbwt (binary outcome, = 1 for <span class="math inline">\(\le\)</span> 2.75 kg, = 0 for &gt; 2.75 kg) / (desfecho binário, = 1 para <span class="math inline">\(\le\)</span> 2,75 kg, = 0 para &gt; 2,75 kg).</li>
</ol>
<p>Neste estudo, iremos realizar uma Análise Exploratória dos Dados, realizando análises descritivas e gráficas, buscando entender as relações entre as variáveis, analisando correlações e associações entre elas. Em seguida, iremos realizar uma Análise de Regressão Linear Simples. O foco desse estudo será analisar a relação das variáveis Idade da Mãe (mageyrs), Idade Gestacional (gestwks), Altura da Mãe (mheightcm) com a variável Peso Ao Nascer (bwtkg).</p>
<section id="carregando-pacotes" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="carregando-pacotes"><span class="header-section-number">1.1</span> Carregando pacotes</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Passo 1: Carregar os pacotes que serao usados</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(pacman)) <span class="fu">install.packages</span>(<span class="st">"pacman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Carregando pacotes exigidos: pacman</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'pacman' was built under R version 4.2.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(readxl, dplyr, ggplot2, car, rstatix, lmtest, ggpubr, skimr, corrplot, haven)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="leitura-dos-dados" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="leitura-dos-dados"><span class="header-section-number">1.2</span> Leitura dos Dados</h2>
<section id="carregando-os-dados" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="carregando-os-dados"><span class="header-section-number">1.2.1</span> Carregando os Dados</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>dados_all <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"chdsmetric.dta"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(dados_all)        <span class="co"># Visualizacao de um resumo dos dados</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 680
Columns: 13
$ bwtkg      &lt;dbl&gt; 3.31, 3.63, 3.40, 3.18, 2.40, 3.90, 4.13, 2.95, 1.50, 3.67,…
$ blengthcm  &lt;dbl&gt; 50.80, 53.34, 53.34, 50.80, 48.26, 50.80, 55.88, 48.26, 50.…
$ bheadcircm &lt;dbl&gt; 33.02, 33.02, 33.02, 33.02, 33.02, 35.56, 38.10, 33.02, 30.…
$ gestwks    &lt;dbl&gt; 37, 41, 39, 39, 37, 43, 40, 37, 29, 41, 40, 39, 41, 41, 42,…
$ mageyrs    &lt;dbl&gt; 33, 28, 32, 27, 32, 30, 23, 27, 32, 28, 26, 19, 37, 31, 29,…
$ mheightcm  &lt;dbl&gt; 167.64, 160.02, 154.94, 172.72, 170.18, 160.02, 165.10, 162…
$ mweightkg  &lt;dbl&gt; 63.50, 58.97, 57.15, 68.04, 50.80, 59.42, 60.78, 56.70, 64.…
$ mcig       &lt;dbl&gt; 25, 0, 0, 2, 17, 0, 0, 17, 0, 0, 25, 0, 25, 17, 0, 0, 0, 0,…
$ fageyrs    &lt;dbl&gt; 37, 35, 38, 30, 28, 34, 26, 29, 32, 41, 26, 27, 46, 38, 30,…
$ fheightcm  &lt;dbl&gt; 187.96, 180.34, 165.10, 185.42, 180.34, 167.64, 180.34, 180…
$ fedyrs     &lt;dbl&gt; 12, 10, 12, 16, 10, 12, 12, 12, 14, 16, 16, 12, 16, 16, 16,…
$ fcig       &lt;dbl&gt; 25, 7, 17, 7, 17, 17, 0, 7, 0, 0, 25, 2, 0, 17, 0, 2, 12, 0…
$ lowbwt     &lt;dbl&gt; 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…</code></pre>
</div>
</div>
</section>
<section id="variáveis-de-interesse" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="variáveis-de-interesse"><span class="header-section-number">1.2.2</span> Variáveis de Interesse</h3>
<p>Nesta análise estatística, iremos focar nas variáveis gestwks, mageyrs, mheightcm e bwtkg.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">select</span>(dados_all, gestwks, mageyrs, mheightcm, bwtkg)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(dados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 680
Columns: 4
$ gestwks   &lt;dbl&gt; 37, 41, 39, 39, 37, 43, 40, 37, 29, 41, 40, 39, 41, 41, 42, …
$ mageyrs   &lt;dbl&gt; 33, 28, 32, 27, 32, 30, 23, 27, 32, 28, 26, 19, 37, 31, 29, …
$ mheightcm &lt;dbl&gt; 167.64, 160.02, 154.94, 172.72, 170.18, 160.02, 165.10, 162.…
$ bwtkg     &lt;dbl&gt; 3.31, 3.63, 3.40, 3.18, 2.40, 3.90, 4.13, 2.95, 1.50, 3.67, …</code></pre>
</div>
</div>
</section>
<section id="visualizando-os-dados" class="level3" data-number="1.2.3">
<h3 data-number="1.2.3" class="anchored" data-anchor-id="visualizando-os-dados"><span class="header-section-number">1.2.3</span> Visualizando os Dados</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(dados[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>,])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">gestwks</th>
<th style="text-align: right;">mageyrs</th>
<th style="text-align: right;">mheightcm</th>
<th style="text-align: right;">bwtkg</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">37</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">167.64</td>
<td style="text-align: right;">3.31</td>
</tr>
<tr class="even">
<td style="text-align: right;">41</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">160.02</td>
<td style="text-align: right;">3.63</td>
</tr>
<tr class="odd">
<td style="text-align: right;">39</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">154.94</td>
<td style="text-align: right;">3.40</td>
</tr>
<tr class="even">
<td style="text-align: right;">39</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">172.72</td>
<td style="text-align: right;">3.18</td>
</tr>
<tr class="odd">
<td style="text-align: right;">37</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">170.18</td>
<td style="text-align: right;">2.40</td>
</tr>
<tr class="even">
<td style="text-align: right;">43</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">160.02</td>
<td style="text-align: right;">3.90</td>
</tr>
<tr class="odd">
<td style="text-align: right;">40</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">165.10</td>
<td style="text-align: right;">4.13</td>
</tr>
<tr class="even">
<td style="text-align: right;">37</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">162.56</td>
<td style="text-align: right;">2.95</td>
</tr>
<tr class="odd">
<td style="text-align: right;">29</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">162.56</td>
<td style="text-align: right;">1.50</td>
</tr>
<tr class="even">
<td style="text-align: right;">41</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">167.64</td>
<td style="text-align: right;">3.67</td>
</tr>
<tr class="odd">
<td style="text-align: right;">40</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">154.94</td>
<td style="text-align: right;">3.54</td>
</tr>
<tr class="even">
<td style="text-align: right;">39</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">165.10</td>
<td style="text-align: right;">3.63</td>
</tr>
<tr class="odd">
<td style="text-align: right;">41</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">160.02</td>
<td style="text-align: right;">3.54</td>
</tr>
<tr class="even">
<td style="text-align: right;">41</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">154.94</td>
<td style="text-align: right;">3.95</td>
</tr>
<tr class="odd">
<td style="text-align: right;">42</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">167.64</td>
<td style="text-align: right;">3.86</td>
</tr>
<tr class="even">
<td style="text-align: right;">42</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">170.18</td>
<td style="text-align: right;">3.67</td>
</tr>
<tr class="odd">
<td style="text-align: right;">40</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">167.64</td>
<td style="text-align: right;">3.49</td>
</tr>
<tr class="even">
<td style="text-align: right;">41</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">172.72</td>
<td style="text-align: right;">3.45</td>
</tr>
<tr class="odd">
<td style="text-align: right;">39</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">172.72</td>
<td style="text-align: right;">3.45</td>
</tr>
<tr class="even">
<td style="text-align: right;">42</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">152.40</td>
<td style="text-align: right;">3.58</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
</section>
<section id="análise-exploratória-dos-dados" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Análise Exploratória dos Dados</h1>
<p>Iremos realizar uma análise exploratória dos dados, buscando extrair informações e observar possíveis correlações entre as variáveis.</p>
<section id="resumo-dos-dados" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="resumo-dos-dados"><span class="header-section-number">2.1</span> Resumo dos Dados</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(dados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">dados</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">680</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">gestwks</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">39.77</td>
<td style="text-align: right;">1.88</td>
<td style="text-align: right;">29.00</td>
<td style="text-align: right;">39.00</td>
<td style="text-align: right;">40.00</td>
<td style="text-align: right;">41.00</td>
<td style="text-align: right;">48.00</td>
<td style="text-align: left;">▁▁▇▃▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">mageyrs</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">25.86</td>
<td style="text-align: right;">5.46</td>
<td style="text-align: right;">15.00</td>
<td style="text-align: right;">21.00</td>
<td style="text-align: right;">25.00</td>
<td style="text-align: right;">29.00</td>
<td style="text-align: right;">42.00</td>
<td style="text-align: left;">▅▇▇▂▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mheightcm</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">163.66</td>
<td style="text-align: right;">6.31</td>
<td style="text-align: right;">144.78</td>
<td style="text-align: right;">160.02</td>
<td style="text-align: right;">162.56</td>
<td style="text-align: right;">167.64</td>
<td style="text-align: right;">180.34</td>
<td style="text-align: left;">▁▃▇▅▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">bwtkg</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.41</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">1.50</td>
<td style="text-align: right;">3.08</td>
<td style="text-align: right;">3.45</td>
<td style="text-align: right;">3.72</td>
<td style="text-align: right;">5.17</td>
<td style="text-align: left;">▁▂▇▃▁</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="análise-descritiva-das-variáveis" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="análise-descritiva-das-variáveis"><span class="header-section-number">2.2</span> Análise Descritiva das Variáveis</h2>
<p>Nesta seção, iremos analisar as variáveis de forma univariada, fazendo uso de testes de normalidade e gráficos do tipo histograma, boxplot e densidade.</p>
<section id="idade-gestacional-gestwks" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="idade-gestacional-gestwks"><span class="header-section-number">2.2.1</span> Idade Gestacional (gestwks)</h3>
<p>Teste Normalidade Shapiro-Wilk</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(dados<span class="sc">$</span>gestwks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  dados$gestwks
W = 0.93902, p-value = 4.551e-16</code></pre>
</div>
</div>
<p>Como o Valor p &lt; 0.05, logo podemos concluir que a variável Idade Gestacional não segue a distribuição normal.</p>
<p>Gráficos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(dados<span class="sc">$</span>gestwks, <span class="at">main =</span> <span class="st">"Histograma de Idade Gestacional"</span>, <span class="at">xlab =</span> <span class="st">"Idade Gestacional (em semanas)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>dados <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>( <span class="fu">aes</span>(<span class="at">x=</span>mageyrs)) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_density</span>(<span class="at">fill=</span><span class="st">"#69b3a2"</span>, <span class="at">color=</span><span class="st">"#e9ecef"</span>, <span class="at">alpha=</span><span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Distribuição de Idade Gestacional"</span>) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"Idade Gestacional (em semanas)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(dados<span class="sc">$</span>gestwks,<span class="at">main =</span> <span class="st">"Boxplot de Idade Gestacional"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-7-3.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="altura-da-mãe-mheightcm" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="altura-da-mãe-mheightcm"><span class="header-section-number">2.2.2</span> Altura da Mãe (mheightcm)</h3>
<p>Teste Normalidade Shapiro-Wilk</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(dados<span class="sc">$</span>mheightcm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  dados$mheightcm
W = 0.98429, p-value = 1.098e-06</code></pre>
</div>
</div>
<p>Como o Valor p &lt; 0.05, logo podemos concluir que a variável Altura da Mãe não segue a distribuição normal.</p>
<p>Gráficos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(dados<span class="sc">$</span>mheightcm, <span class="at">main =</span> <span class="st">"Histograma de Altura da Mãe"</span>, <span class="at">xlab =</span> <span class="st">"Altura (em cm)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>dados <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>( <span class="fu">aes</span>(<span class="at">x=</span>mheightcm)) <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_density</span>(<span class="at">fill=</span><span class="st">"#69b3a2"</span>, <span class="at">color=</span><span class="st">"#e9ecef"</span>, <span class="at">alpha=</span><span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Distribuição de Altura da Mãe"</span>) <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"Altura (em cm)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(dados<span class="sc">$</span>mheightcm, <span class="at">main =</span> <span class="st">"Boxplot de Altura da Mãe"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-9-3.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="idade-da-mãe-mageyrs" class="level3" data-number="2.2.3">
<h3 data-number="2.2.3" class="anchored" data-anchor-id="idade-da-mãe-mageyrs"><span class="header-section-number">2.2.3</span> Idade da Mãe (mageyrs)</h3>
<p>Teste Normalidade Shapiro-Wilk</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(dados<span class="sc">$</span>mageyrs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  dados$mageyrs
W = 0.95297, p-value = 6.537e-14</code></pre>
</div>
</div>
<p>Como o Valor p &lt; 0.05, logo podemos concluir que a variável Idade da Mãe não segue a distribuição normal.</p>
<p>Gráficos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(dados<span class="sc">$</span>mageyrs, <span class="at">main =</span> <span class="st">"Histograma de Idade da Mãe"</span>, <span class="at">xlab =</span> <span class="st">"Idade (em anos)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>dados <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>( <span class="fu">aes</span>(<span class="at">x=</span>mageyrs)) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_density</span>(<span class="at">fill=</span><span class="st">"#69b3a2"</span>, <span class="at">color=</span><span class="st">"#e9ecef"</span>, <span class="at">alpha=</span><span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Distribuição de Idade da Mãe"</span>) <span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"Idade (em anos)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(dados<span class="sc">$</span>mageyrs, <span class="at">main =</span> <span class="st">"Boxplot de Idade da Mãe"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-11-3.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="peso-ao-nascer-bwtkg" class="level3" data-number="2.2.4">
<h3 data-number="2.2.4" class="anchored" data-anchor-id="peso-ao-nascer-bwtkg"><span class="header-section-number">2.2.4</span> Peso ao Nascer (bwtkg)</h3>
<section id="teste-normalidade-shapiro-wilk" class="level4">
<h4 class="anchored" data-anchor-id="teste-normalidade-shapiro-wilk">Teste Normalidade Shapiro-Wilk</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(dados<span class="sc">$</span>bwtkg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  dados$bwtkg
W = 0.99639, p-value = 0.1244</code></pre>
</div>
</div>
<p>Como o valor p &gt; 0.05, podemos concluir que a variável Peso ao Nascer segue a distribuição normal.</p>
<section id="gráficos" class="level5">
<h5 class="anchored" data-anchor-id="gráficos">Gráficos:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(dados<span class="sc">$</span>bwtkg, <span class="at">main =</span> <span class="st">"Histograma de Peso ao Nascer"</span>, <span class="at">xlab =</span> <span class="st">"Peso (em kg)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>dados <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>( <span class="fu">aes</span>(<span class="at">x=</span>bwtkg)) <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_density</span>(<span class="at">fill=</span><span class="st">"#69b3a2"</span>, <span class="at">color=</span><span class="st">"#e9ecef"</span>, <span class="at">alpha=</span><span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Distribuição de Peso ao Nascer"</span>) <span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"Peso (em kg)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(dados<span class="sc">$</span>bwtkg, <span class="at">main =</span> <span class="st">"Boxplot de Peso ao Nascer"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-13-3.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>
<section id="observações-importantes" class="level3" data-number="2.2.5">
<h3 data-number="2.2.5" class="anchored" data-anchor-id="observações-importantes"><span class="header-section-number">2.2.5</span> Observações Importantes</h3>
<p>Observando os gráficos de boxplot das variáveis, notamos a presença de outliers em todas as variáveis do conjunto de dados sendo estudado. Analisando os testes de normalidade feitos, nota-se que apenas a variável Peso ao Nascer (bwtkg) segue a distribuição normal. Com isso, optamos por utilizar também o Teste de Spearman para analisar correlações entre variáveis.</p>
</section>
</section>
<section id="analisando-correlações-entre-variáveis" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="analisando-correlações-entre-variáveis"><span class="header-section-number">2.3</span> Analisando Correlações entre Variáveis</h2>
<p>Nesta seção iremos analisar as variáveis de forma bi-variada, buscando visualizar possíveis correlações entre as variáveis Idade da Mãe(mageyrs), Altura da Mãe(mheightcm) e Idade Gestacional(gestwks) com a variável Peso ao Nascer(bwtkg).</p>
<section id="idade-gestacional-e-peso-ao-nascer" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="idade-gestacional-e-peso-ao-nascer"><span class="header-section-number">2.3.1</span> Idade Gestacional e Peso ao Nascer</h3>
<section id="visualizando-relações-entre-variáveis" class="level4">
<h4 class="anchored" data-anchor-id="visualizando-relações-entre-variáveis">Visualizando Relações entre Variáveis</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dados<span class="sc">$</span>gestwks, dados<span class="sc">$</span>bwtkg, <span class="at">xlab=</span><span class="st">"Idade Gestacional"</span>, <span class="at">ylab=</span><span class="st">"Peso ao Nascer"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="coeficiente-de-correlação" class="level4">
<h4 class="anchored" data-anchor-id="coeficiente-de-correlação">Coeficiente de Correlação</h4>
<p>Estimativa do coeficiente de correlação (linear) entre variáveis numéricas.</p>
<p>Coeficiente de Pearson:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(dados<span class="sc">$</span>bwtkg, dados<span class="sc">$</span>gestwks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4259589</code></pre>
</div>
</div>
<p>Coeficiente de Spearman:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(dados<span class="sc">$</span>bwtkg, dados<span class="sc">$</span>gestwks, <span class="at">method=</span><span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4050987</code></pre>
</div>
</div>
</section>
</section>
<section id="altura-da-mãe-e-peso-ao-nascer" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="altura-da-mãe-e-peso-ao-nascer"><span class="header-section-number">2.3.2</span> Altura da Mãe e Peso ao Nascer</h3>
<section id="visualizando-relações-entre-variáveis-1" class="level4">
<h4 class="anchored" data-anchor-id="visualizando-relações-entre-variáveis-1">Visualizando Relações entre Variáveis</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dados<span class="sc">$</span>mheightcm, dados<span class="sc">$</span>bwtkg, <span class="at">xlab=</span><span class="st">"Altura da Mãe"</span>, <span class="at">ylab=</span><span class="st">"Peso ao Nascer"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="coeficiente-de-correlação-1" class="level4">
<h4 class="anchored" data-anchor-id="coeficiente-de-correlação-1">Coeficiente de Correlação</h4>
<p>Estimativa do coeficiente de correlação (linear) entre variáveis numéricas.</p>
<p>Coeficiente de Pearson:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(dados<span class="sc">$</span>bwtkg, dados<span class="sc">$</span>mheightcm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2025446</code></pre>
</div>
</div>
<p>Coeficiente de Spearman:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(dados<span class="sc">$</span>bwtkg, dados<span class="sc">$</span>mheightcm, <span class="at">method=</span><span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1996057</code></pre>
</div>
</div>
</section>
</section>
<section id="idade-da-mãe-e-peso-ao-nascer" class="level3" data-number="2.3.3">
<h3 data-number="2.3.3" class="anchored" data-anchor-id="idade-da-mãe-e-peso-ao-nascer"><span class="header-section-number">2.3.3</span> Idade da Mãe e Peso ao Nascer</h3>
<section id="visualizando-relações-entre-variáveis-2" class="level4">
<h4 class="anchored" data-anchor-id="visualizando-relações-entre-variáveis-2">Visualizando Relações entre Variáveis</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dados<span class="sc">$</span>mageyrs, dados<span class="sc">$</span>bwtkg, <span class="at">xlab=</span><span class="st">"Idade da Mãe"</span>, <span class="at">ylab=</span><span class="st">"Peso ao Nascer"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="coeficiente-de-correlação-2" class="level4">
<h4 class="anchored" data-anchor-id="coeficiente-de-correlação-2">Coeficiente de Correlação</h4>
<p>Estimativa do coeficiente de correlação (linear) entre variáveis numéricas.</p>
<p>Coeficiente de Pearson:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(dados<span class="sc">$</span>bwtkg, dados<span class="sc">$</span>mageyrs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0009591992</code></pre>
</div>
</div>
<p>Coeficiente de Spearman:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(dados<span class="sc">$</span>bwtkg, dados<span class="sc">$</span>mageyrs, <span class="at">method=</span><span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02201139</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="visualizando-a-correlação-das-4-variáveis" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="visualizando-a-correlação-das-4-variáveis"><span class="header-section-number">2.4</span> Visualizando a Correlação das 4 Variáveis</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>matrix.cor <span class="ot">&lt;-</span> <span class="fu">cor</span>(dados, <span class="at">method=</span><span class="st">"spearman"</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(matrix.cor, <span class="at">method=</span><span class="st">"color"</span>, <span class="at">addCoef.col=</span><span class="st">"black"</span>, <span class="at">type=</span><span class="st">"upper"</span>, <span class="at">diag=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-23-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="análise-indutiva" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Análise Indutiva</h1>
<p>Analisando os resultados obtidos na seção anterior, podemos inferir que existe uma correlação moderada entre a Idade Gestacional e o Peso Ao Nascer, com coeficiente de Spearman de 0.40 e de Pearson de 0.42. Também podemos inferir que existe uma correlação fraca entre a Altura da Mãe e o Peso ao Nascer, com coeficiente de Pearson de 0.20 e Coeficiente de Spearman de 0.20. Nota-se que a correlação entre Idade da Mãe e Peso ao Nascer é extremamente fraca ou inexistente, com o Coeficiente de Spearman de 0.02 e Coeficiente de Pearson de 0.001. Com isso, iremos aplicar um teste de hipótese para observar a associação entre essas variáveis.</p>
<section id="peso-ao-nascer-e-idade-gestacional" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="peso-ao-nascer-e-idade-gestacional"><span class="header-section-number">3.1</span> Peso Ao Nascer e Idade Gestacional</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>cor.result.gestwks <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(dados<span class="sc">$</span>gestwks, dados<span class="sc">$</span>bwtkg)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>cor.result.gestwks</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  dados$gestwks and dados$bwtkg
t = 12.259, df = 678, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.3623791 0.4855928
sample estimates:
      cor 
0.4259589 </code></pre>
</div>
</div>
<p>Aplicando um teste de hipótese para verificar a existência de associação entre as variáveis Idade Gestacional e Peso Ao Nascer, encontramos intervalo de confiança entre 0.36 e 0.49. Como este intervalo não contém a correlação nula (=0), podemos concluir com 95% de confiança que existe associação linear e positiva entre essas variáveis. Ou seja, quanto maior o Tempo de Gestação, maior será o Peso ao Nascer do recém-nascido.</p>
</section>
<section id="peso-ao-nascer-e-altura-da-mãe" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="peso-ao-nascer-e-altura-da-mãe"><span class="header-section-number">3.2</span> Peso ao Nascer e Altura da Mãe</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>cor.result.mheightcm <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(dados<span class="sc">$</span>mheightcm, dados<span class="sc">$</span>bwtkg)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>cor.result.mheightcm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  dados$mheightcm and dados$bwtkg
t = 5.3856, df = 678, p-value = 9.968e-08
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.1293287 0.2735640
sample estimates:
      cor 
0.2025446 </code></pre>
</div>
</div>
<p>Aplicando um teste de hipótese para verificar a existência de associação entre as variáveis Altura da Mãe e Peso Ao Nascer, encontramos intervalo de confiança entre 0.13 e 0.27. Como este intervalo não contém a correlação nula (=0), podemos concluir com 95% de confiança que existe associação linear e positiva entre essas variáveis. Ou seja, quanto maior a Altura da Mãe, maior será o Peso ao Nascer do recém-nascido.</p>
</section>
<section id="peso-ao-nascer-e-idade-da-mãe" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="peso-ao-nascer-e-idade-da-mãe"><span class="header-section-number">3.3</span> Peso ao Nascer e Idade da Mãe</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>cor.result.mageyrs <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(dados<span class="sc">$</span>mageyrs, dados<span class="sc">$</span>bwtkg)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>cor.result.mageyrs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  dados$mageyrs and dados$bwtkg
t = 0.024976, df = 678, p-value = 0.9801
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.07423154  0.07613909
sample estimates:
         cor 
0.0009591992 </code></pre>
</div>
</div>
<p>Aplicando um teste de hipótese para verificar a existência de associação entre as variáveis Idade da Mãe e Peso Ao Nascer, encontramos intervalo de confiança entre -0.07 e 0.07. Como este intervalo contém a correlação nula (=0), podemos concluir com 95% de confiança que não existe associação entre essas variáveis.</p>
</section>
</section>
<section id="análise-de-regressão-linear" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Análise de Regressão Linear</h1>
<p>Nessa seção, iremos utilizar Modelos de Regressão Linear Simples para as variáveis <a href="#idade-gestacional-e-peso-ao-nascer-1">Idade Gestacional e Peso ao Nascer</a>, <a href="#idade-da-mãe-e-peso-ao-nascer-1">Idade da Mãe e Peso ao Nascer</a> e <a href="#altura-da-mãe-e-peso-ao-nascer-1">Altura da Mãe e Peso ao Nascer</a>.</p>
<section id="idade-gestacional-e-peso-ao-nascer-1" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="idade-gestacional-e-peso-ao-nascer-1"><span class="header-section-number">4.1</span> Idade Gestacional e Peso Ao Nascer</h2>
<section id="análise-do-modelo" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="análise-do-modelo"><span class="header-section-number">4.1.1</span> Análise do Modelo</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>model.gestwks <span class="ot">&lt;-</span> <span class="fu">lm</span>(bwtkg<span class="sc">~</span>gestwks, dados)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.gestwks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bwtkg ~ gestwks, data = dados)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.43502 -0.28249  0.01492  0.28621  1.50992 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -1.066189   0.365473  -2.917  0.00365 ** 
gestwks      0.112530   0.009179  12.259  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4486 on 678 degrees of freedom
Multiple R-squared:  0.1814,    Adjusted R-squared:  0.1802 
F-statistic: 150.3 on 1 and 678 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Dado que o valor p do F-Statistic suficientemente pequeno, rejeita-se a Hipótese Nula (<span class="math inline">\(\beta = 0\)</span>). Admitindo a Hipótese Alternativa (<span class="math inline">\(\beta \not= 0\)</span>), a Idade Gestacional exerce influência linear sobre o Peso ao Nascer.</p>
<p><span class="math display">\[
y = -1.1 + 0.11x
\]</span></p>
</section>
<section id="verificação-dos-pressupostos-da-regressão-linear" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="verificação-dos-pressupostos-da-regressão-linear"><span class="header-section-number">4.1.2</span> Verificação dos Pressupostos da Regressão Linear</h3>
<section id="análise-gráfica" class="level4">
<h4 class="anchored" data-anchor-id="análise-gráfica">Análise Gráfica</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model.gestwks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>Analisando o Gráfico de Resíduos-Fitted, nota-se que a linha dos resíduos aproxima-se do eixo horizontal do gráfico, porém com um padrão similar a uma parábola, indicando que talvez existam relações não-lineares não explicadas pelo modelo.</li>
<li>Analisando o Gráfico Q-Q Normal, verificamos que os resíduos se aproximam bastante da linha diagonal tracejada, sendo uma boa indicação para o modelo, que os resíduos seguem a distribuição normal.</li>
<li>Analisando o Gráfico Scale-Location, verificamos que os resíduos não estão distribuídos igualmente ao longo de uma linha horizontal, formando padrões ao longo do gráfico, levando ao questionamento da Homocedasticidade.</li>
<li>Analisando o Gráfico de Alavancagem, não há indicações de casos influenciais no estudo (outliers que possam influenciar na regressão linear), todos os casos aparentam estar dentro das linhas da Distância de Cook.</li>
</ul>
</section>
<section id="verificação-por-testes-de-hipótese" class="level4">
<h4 class="anchored" data-anchor-id="verificação-por-testes-de-hipótese">Verificação por Testes de Hipótese</h4>
<section id="teste-de-normalidade-shapiro-wilk" class="level5">
<h5 class="anchored" data-anchor-id="teste-de-normalidade-shapiro-wilk">Teste de Normalidade Shapiro-Wilk</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(model.gestwks<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  model.gestwks$residuals
W = 0.99716, p-value = 0.2848</code></pre>
</div>
</div>
<p>Dado que o valor p não é suficientemente pequeno (0.28), admite-se a Hipótese Nula que os resíduos seguem a distribuição normal.</p>
</section>
<section id="outliers-nos-resíduos" class="level5">
<h5 class="anchored" data-anchor-id="outliers-nos-resíduos">Outliers nos Resíduos</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">rstandard</span>(model.gestwks))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
-3.201361 -0.630276  0.033342 -0.000243  0.638674  3.371924 </code></pre>
</div>
</div>
<p>Espera-se que, seguindo a distribuição normal, os valores estariam entre -3 e 3. Porém os valores mínimos e máximo dos resíduos são -3.2 e 3.37, indicando a presença de possíveis outliers nos dados.</p>
</section>
<section id="independência-dos-resíduos-com-estatística-de-durbin-watson" class="level5">
<h5 class="anchored" data-anchor-id="independência-dos-resíduos-com-estatística-de-durbin-watson">Independência dos Resíduos com Estatística de Durbin-Watson</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">durbinWatsonTest</span>(model.gestwks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> lag Autocorrelation D-W Statistic p-value
   1     -0.01116268      2.018007   0.782
 Alternative hypothesis: rho != 0</code></pre>
</div>
</div>
<p>Dado que a estatística de Durbin-Watson está entre 1 e 3 (2.18), que reforça uma ideia de Independência dos Resíduos. Em seguida, avaliando o valor p, temos que o valor p é suficientemente grande (0.77 &gt; 0.05), não se rejeita a hipótese nula, admitindo que há independência dos resíduos.</p>
</section>
<section id="teste-de-homocedasticidade-breusch-pagan" class="level5">
<h5 class="anchored" data-anchor-id="teste-de-homocedasticidade-breusch-pagan">Teste de Homocedasticidade Breusch-Pagan</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(model.gestwks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  model.gestwks
BP = 2.2613, df = 1, p-value = 0.1326</code></pre>
</div>
</div>
<p>Dado que o valor p do Teste Breusch-Pagan é de 0.13, não se rejeita a hipótese nula. Logo, podemos concluir que o modelo é homocedástico.</p>
</section>
</section>
</section>
<section id="visualização-gráfica" class="level3" data-number="4.1.3">
<h3 data-number="4.1.3" class="anchored" data-anchor-id="visualização-gráfica"><span class="header-section-number">4.1.3</span> Visualização Gráfica</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dados, <span class="at">mapping =</span> <span class="fu">aes</span>(gestwks, bwtkg)) <span class="sc">+</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">col=</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_regline_equation</span>() <span class="sc">+</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="altura-da-mãe-e-peso-ao-nascer-1" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="altura-da-mãe-e-peso-ao-nascer-1"><span class="header-section-number">4.2</span> Altura da Mãe e Peso ao Nascer</h2>
<section id="análise-do-modelo-1" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="análise-do-modelo-1"><span class="header-section-number">4.2.1</span> Análise do Modelo</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>model.mheightcm <span class="ot">&lt;-</span> <span class="fu">lm</span>(bwtkg<span class="sc">~</span>mheightcm, dados)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.mheightcm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bwtkg ~ mheightcm, data = dados)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.89167 -0.31387  0.00833  0.31884  1.81874 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.805332   0.483849   1.664   0.0965 .  
mheightcm   0.015910   0.002954   5.386 9.97e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4855 on 678 degrees of freedom
Multiple R-squared:  0.04102,   Adjusted R-squared:  0.03961 
F-statistic:    29 on 1 and 678 DF,  p-value: 9.968e-08</code></pre>
</div>
</div>
<p>Dado que o valor p do F-Statistic suficientemente pequeno, rejeita-se a Hipótese Nula (<span class="math inline">\(\beta = 0\)</span>). Admitindo a Hipótese Alternativa (<span class="math inline">\(\beta \not= 0\)</span>), a Altura da Mãe exerce influência linear sobre o Peso ao Nascer.</p>
<p><span class="math display">\[
y = 0.8 +0.016x
\]</span></p>
</section>
<section id="verificação-dos-pressupostos-da-regressão-linear-1" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="verificação-dos-pressupostos-da-regressão-linear-1"><span class="header-section-number">4.2.2</span> Verificação dos Pressupostos da Regressão Linear</h3>
<section id="análise-gráfica-1" class="level4">
<h4 class="anchored" data-anchor-id="análise-gráfica-1">Análise Gráfica</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model.mheightcm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>Analisando o Gráfico de Resíduos-Fitted, nota-se que a linha dos resíduos aproxima-se de uma linha horizontal sem padrões que possam ser distinguidos, indicando que não há relações não-lineares das variáveis nos dados, e indicando uma relação linear entre as variáveis.</li>
<li>Analisando o Gráfico Q-Q Normal, verificamos que os resíduos se aproximam bastante da linha diagonal tracejada, sendo uma boa indicação para o modelo, que os resíduos seguem a distribuição normal.</li>
<li>Analisando o Gráfico Scale-Location, verificamos que os resíduos estão distribuídos pelo gráfico, formando padrões em linhas verticais, não distribuídos igualmente. Essa observação leva ao questionanamento da Homocedasticidade.</li>
<li>Analisando o Gráfico de Alavancagem, não há indicações de casos influenciais no estudo (outliers que possam influenciar na regressão linear), todos os casos aparentam estar dentro das linhas da Distância de Cook.</li>
</ul>
</section>
<section id="verificação-por-testes-de-hipótese-1" class="level4">
<h4 class="anchored" data-anchor-id="verificação-por-testes-de-hipótese-1">Verificação por Testes de Hipótese</h4>
<section id="teste-de-normalidade-shapiro-wilk-1" class="level5">
<h5 class="anchored" data-anchor-id="teste-de-normalidade-shapiro-wilk-1">Teste de Normalidade Shapiro-Wilk</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(model.mheightcm<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  model.mheightcm$residuals
W = 0.99684, p-value = 0.2048</code></pre>
</div>
</div>
<p>Dado que o valor p não é suficientemente pequeno (0.20), admite-se a Hipótese Nula que os resíduos seguem a distribuição normal.</p>
</section>
<section id="outliers-nos-resíduos-1" class="level5">
<h5 class="anchored" data-anchor-id="outliers-nos-resíduos-1">Outliers nos Resíduos</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">rstandard</span>(model.mheightcm))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
-3.898959 -0.647143  0.017160 -0.000015  0.657389  3.749465 </code></pre>
</div>
</div>
<p>Espera-se que, seguindo a distribuição normal, os valores estariam entre -3 e 3. Porém os valores mínimos e máximo dos resíduos são -3.9 e 3.75, indicando a presença de outliers nos dados.</p>
</section>
<section id="independência-dos-resíduos-com-estatística-de-durbin-watson-1" class="level5">
<h5 class="anchored" data-anchor-id="independência-dos-resíduos-com-estatística-de-durbin-watson-1">Independência dos Resíduos com Estatística de Durbin-Watson</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">durbinWatsonTest</span>(model.mheightcm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> lag Autocorrelation D-W Statistic p-value
   1     -0.01932041       2.03573   0.618
 Alternative hypothesis: rho != 0</code></pre>
</div>
</div>
<p>Dado que a estatística de Durbin-Watson está entre 1 e 3 (2.03), que reforça uma ideia de Independência dos Resíduos. Em seguida, avaliando o valor p, temos que o valor p é suficientemente grande (0.68 &gt; 0.05), não se rejeita a hipótese nula, admitindo que há independência dos resíduos.</p>
</section>
</section>
<section id="teste-de-homocedasticidade-breusch-pagan-1" class="level4">
<h4 class="anchored" data-anchor-id="teste-de-homocedasticidade-breusch-pagan-1">Teste de Homocedasticidade Breusch-Pagan</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(model.mheightcm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  model.mheightcm
BP = 0.2296, df = 1, p-value = 0.6318</code></pre>
</div>
</div>
<p>Dado que o valor p do Teste Breusch-Pagan é de 0.64, consideravelmente maior que 0.05, logo, não se rejeita a hipótese nula e podemos concluir que o modelo é homocedástico.</p>
</section>
</section>
<section id="visualização-gráfica-1" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="visualização-gráfica-1"><span class="header-section-number">4.2.3</span> Visualização Gráfica</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dados, <span class="at">mapping =</span> <span class="fu">aes</span>(mheightcm, bwtkg)) <span class="sc">+</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">col=</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_regline_equation</span>() <span class="sc">+</span></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="idade-da-mãe-e-peso-ao-nascer-1" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="idade-da-mãe-e-peso-ao-nascer-1"><span class="header-section-number">4.3</span> Idade da Mãe e Peso ao Nascer</h2>
<section id="análise-do-modelo-2" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="análise-do-modelo-2"><span class="header-section-number">4.3.1</span> Análise do Modelo</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>model.mageyrs <span class="ot">&lt;-</span> <span class="fu">lm</span>(bwtkg<span class="sc">~</span>mageyrs, dados)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.mageyrs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bwtkg ~ mageyrs, data = dados)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.90974 -0.32939  0.03974  0.31133  1.76000 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 3.407e+00  9.204e-02  37.016   &lt;2e-16 ***
mageyrs     8.699e-05  3.483e-03   0.025     0.98    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4958 on 678 degrees of freedom
Multiple R-squared:  9.201e-07, Adjusted R-squared:  -0.001474 
F-statistic: 0.0006238 on 1 and 678 DF,  p-value: 0.9801</code></pre>
</div>
</div>
<p>Dado que o valor p do F-Statistic não é suficientemente pequeno, admite-se a Hipótese Nula (<span class="math inline">\(\beta = 0\)</span>), a Idade da Mãe não exerce influência linear sobre o Peso ao Nascer.</p>
<p><span class="math display">\[
y = 3.4 +8.7*10^{-5}x
\]</span></p>
</section>
<section id="verificação-dos-pressupostos-da-regressão-linear-2" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="verificação-dos-pressupostos-da-regressão-linear-2"><span class="header-section-number">4.3.2</span> Verificação dos Pressupostos da Regressão Linear</h3>
<section id="análise-gráfica-2" class="level4">
<h4 class="anchored" data-anchor-id="análise-gráfica-2">Análise Gráfica</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model.mageyrs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>Analisando o Gráfico de Resíduos-Fitted, nota-se que a linha dos resíduos aproxima-se de uma linha horizontal sem padrões que possam ser distinguidos, indicando que não há relações não-lineares que possam ser percebidas, indicando uma relação linear entre as variáveis.</li>
<li>Analisando o Gráfico Q-Q Normal, verificamos que os resíduos se aproximam bastante da linha diagonal tracejada, sendo uma boa indicação para o modelo que os resíduos seguem a distribuição normal.</li>
<li>Analisando o Gráfico Scale-Location, verificamos que os resíduos estão distribuídos pelo gráfico, formando padrões em linhas verticais, não distribuídos igualmente. Essa observação leva ao questionanamento da Homocedasticidade.</li>
<li>Analisando o Gráfico de Alavancagem, não há indicações de casos influenciais no estudo (outliers que possam influenciar na regressão linear), todos os casos aparentam estar dentro das linhas da Distância de Cook.</li>
</ul>
</section>
<section id="verificação-por-testes-de-hipótese-2" class="level4">
<h4 class="anchored" data-anchor-id="verificação-por-testes-de-hipótese-2">Verificação por Testes de Hipótese</h4>
<section id="teste-de-normalidade-shapiro-wilk-2" class="level5">
<h5 class="anchored" data-anchor-id="teste-de-normalidade-shapiro-wilk-2">Teste de Normalidade Shapiro-Wilk</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(model.mageyrs<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  model.mageyrs$residuals
W = 0.99644, p-value = 0.1325</code></pre>
</div>
</div>
<p>Dado que o valor p não é suficientemente pequeno (0.13), admite-se a Hipótese Nula que os resíduos seguem a distribuição normal.</p>
</section>
<section id="outliers-nos-resíduos-2" class="level5">
<h5 class="anchored" data-anchor-id="outliers-nos-resíduos-2">Outliers nos Resíduos</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">rstandard</span>(model.mageyrs))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
-3.858123 -0.664905  0.080530 -0.000079  0.628947  3.559653 </code></pre>
</div>
</div>
<p>Espera-se que, seguindo a distribuição normal, os valores dos resíduos estariam entre -3 e 3. Porém os valores mínimos e máximo dos resíduos são -3.86 e 3.56, indicando existe a presença de outliers nos dados.</p>
</section>
<section id="independência-dos-resíduos-com-estatística-de-durbin-watson-2" class="level5">
<h5 class="anchored" data-anchor-id="independência-dos-resíduos-com-estatística-de-durbin-watson-2">Independência dos Resíduos com Estatística de Durbin-Watson</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">durbinWatsonTest</span>(model.mageyrs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> lag Autocorrelation D-W Statistic p-value
   1     0.005735402      1.986317   0.852
 Alternative hypothesis: rho != 0</code></pre>
</div>
</div>
<p>Dado que a estatística de Durbin-Watson está entre 1 e 3 (1.98), que reforça uma ideia de Independência dos Resíduos. Em seguida, avaliando o valor p, temos que o valor p é suficientemente grande (0.85 &gt; 0.05), logo, não se rejeita a hipótese nula, admitindo que existe independência dos resíduos.</p>
</section>
<section id="teste-de-homocedasticidade-breusch-pagan-2" class="level5">
<h5 class="anchored" data-anchor-id="teste-de-homocedasticidade-breusch-pagan-2">Teste de Homocedasticidade Breusch-Pagan</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(model.mageyrs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  model.mageyrs
BP = 0.34671, df = 1, p-value = 0.556</code></pre>
</div>
</div>
<p>Dado que o valor p do Teste Breusch-Pagan é de 0.56, consideravelmente maior que 0.05, logo, não se rejeita a hipótese nula e podemos concluir que o modelo é homocedástico.</p>
</section>
</section>
</section>
<section id="visualização-gráfica-2" class="level3" data-number="4.3.3">
<h3 data-number="4.3.3" class="anchored" data-anchor-id="visualização-gráfica-2"><span class="header-section-number">4.3.3</span> Visualização Gráfica</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dados, <span class="at">mapping =</span> <span class="fu">aes</span>(mageyrs, bwtkg)) <span class="sc">+</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">col=</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_regline_equation</span>() <span class="sc">+</span></span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="relatorio_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>
<section id="conclusão" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Conclusão</h1>
<p>Através dos Testes do Pressuposto realizados, podemos concluir que os modelos de regressão linear gerados atendem aos pressupostos da regressão linear, logo apresentam confiabilidade.</p>
<p>Analisando os resultados obtidos pelos Modelos de Regressão Linear, Análise de Correlação e pelos gráficos desenvolvidos, podemos concluir que os fatores Idades Gestacional e Altura da Mãe possuem relação de associação linear positiva com a variável Peso Ao Nascer. Observando os coeficientes de correlação e os modelos de regressão linear, podemos observar que o fator Idade Gestacional possui uma influência maior sobre o Peso quando comparado ao fator Altura da Mãe. Também podemos concluir que o fator Idade da Mãe não possui influência linear sobre o Peso ao Nascer, e possui correlação extremamente fraca e neglível com essa variável.</p>
<p>Resumindo os resultados obtidos, podemos derivar as seguintes conclusões desse estudo:</p>
<ul>
<li>Os fatores Idade Gestacional e Altura da Mãe possuem influência linear sobre o fator Peso ao Nascer da criança.</li>
<li>O fator Idade Gestacional é o fator mais relevante para se prever a variável Peso ao Nascer, dentre os fatores analisados.</li>
<li>O fator Idade da Mãe não é relevante para prever a variável Peso ao Nascer, por não possuir correlação significativa e não possuir influência linear.</li>
<li>Os pressupostos do modelo de regressão linear são satisfeitas para todos os 3 modelos criados.</li>
</ul>
<section id="realizando-previsões-de-peso-ao-nascer" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="realizando-previsões-de-peso-ao-nascer"><span class="header-section-number">5.1</span> Realizando Previsões De Peso ao Nascer</h2>
<p>Para finalizar o estudo, utilizaremos os modelos de regressão para realizar previsões de Peso ao Nascer de uma criança a partir das variáveis de Idade Gestacional, Altura da Mãe e Idade da Mãe.</p>
<section id="a-partir-na-idade-gestacional" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="a-partir-na-idade-gestacional"><span class="header-section-number">5.1.1</span> A partir na Idade Gestacional</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>gestacaoX <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">38</span>, <span class="dv">43</span>, <span class="dv">36</span>, <span class="dv">39</span>)</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>df.gestacaoX <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="st">"gestwks"</span> <span class="ot">=</span> gestacaoX)</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>previsoes.gestacao <span class="ot">&lt;-</span> <span class="fu">predict</span>(model.gestwks, df.gestacaoX)</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>resultados.gestacao <span class="ot">&lt;-</span> <span class="fu">cbind</span>(gestacaoX, previsoes.gestacao)</span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>resultados.gestacao</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  gestacaoX previsoes.gestacao
1        38           3.209961
2        43           3.772612
3        36           2.984901
4        39           3.322491</code></pre>
</div>
</div>
</section>
<section id="a-partir-da-altura-da-mãe" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="a-partir-da-altura-da-mãe"><span class="header-section-number">5.1.2</span> A partir da Altura da Mãe</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>alturaX <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">164</span>, <span class="dv">180</span>, <span class="dv">146</span>, <span class="dv">172</span>)</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>df.alturaX <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="st">"mheightcm"</span> <span class="ot">=</span> alturaX)</span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>previsoes.altura <span class="ot">&lt;-</span> <span class="fu">predict</span>(model.mheightcm, df.alturaX)</span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>resultados.altura <span class="ot">&lt;-</span> <span class="fu">cbind</span>(alturaX, previsoes.altura)</span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a>resultados.altura</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  alturaX previsoes.altura
1     164         3.414585
2     180         3.669146
3     146         3.128203
4     172         3.541866</code></pre>
</div>
</div>
</section>
<section id="a-partir-da-idade-da-mãe" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="a-partir-da-idade-da-mãe"><span class="header-section-number">5.1.3</span> A partir da Idade da Mãe</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>idadeX <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">27</span>, <span class="dv">37</span>, <span class="dv">22</span>, <span class="dv">54</span>)</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>df.idadeX <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="st">"mageyrs"</span> <span class="ot">=</span> idadeX)</span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>previsoes.idade <span class="ot">&lt;-</span> <span class="fu">predict</span>(model.mageyrs, df.idadeX)</span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a>resultados.idade <span class="ot">&lt;-</span> <span class="fu">cbind</span>(idadeX, previsoes.idade)</span>
<span id="cb97-6"><a href="#cb97-6" aria-hidden="true" tabindex="-1"></a>resultados.idade</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  idadeX previsoes.idade
1     27        3.409305
2     37        3.410175
3     22        3.408870
4     54        3.411654</code></pre>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>